services:
  mysql:
    container_name: 'pokedle-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=pokedle'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=secret'
      - 'MYSQL_USER=user'
    ports:
      - '3307:3306'
