spring.application.name=pokedle-maven

spring.datasource.url=jdbc:postgresql://dpg-d6r8o915pdvs73bmb3qg-a.oregon-postgres.render.com:5432/pokedle
spring.datasource.username=root
spring.datasource.password=ulSnpL9F2CrGxApQZ2cfkdNCqvyXto0q


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

server.port=${PORT:8080}